# Generated by Django 5.2 on 2025-04-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_blacklisttoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistToken',
        ),
    ]
