# Generated by Django 5.1.7 on 2025-04-09 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('jarayonda', 'Jarayonda'), ('yuborilgan', 'Yuborilgan'), ('yetkazilgan', 'Yetkazilgan'), ('bekor qilingan', 'Bekor qilingan')], default='kutilmoqda', max_length=50)),
                ('shipping_address', models.TextField()),
                ('payment_method', models.CharField(choices=[('by card', 'Kredit karta'), ('PayPal', 'PayPal'), ('with bank', "Bank o'tkazmasi"), ('COD', "Yetkazib berishda to'lash")], default='by card', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
